coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "test/**/*"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/stories/**"
  - "**/*.stories.tsx"
  - "**/*.stories.ts" 